version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: staff_postgres
    environment:
      POSTGRES_DB: staff_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5205:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - staff-network

  backend:
    build: ./Backend
    container_name: staff_backend
    depends_on:
      - postgres
    environment:
      PORT: 3205
    ports:
      - "3205:3205"
    networks:
      - staff-network

  hr-staff:
    build: ./HR-staff
    container_name: hr_staff_ui
    ports:
      - "8010:80"
    networks:
      - staff-network

volumes:
  postgres_data:

networks:
  staff-network:

