version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-staff
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: staff_management
    volumes:
      - pgdata-staff:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend-staff
    ports:
      - "3006:3006"
    depends_on:
      - postgres

  hr-staff-ui:
    build: ./HR-staff
    container_name: hr-staff-ui
    ports:
      - "8009:80"

volumes:
  pgdata-staff:

