version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: staff_postgres
    environment:
      POSTGRES_DB: staff_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5205:5432"
    volumes:
      - pgdata-staff:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend-staff
    ports:
      - "3006:3006"
    depends_on:
      - postgres
    environment:
      PORT: 3205
    ports:
      - "3205:3205"
    networks:
      - staff-network

  hr-staff-ui:
    build: ./HR-staff
    container_name: hr-staff-ui
    ports:
      - "8010:80"
    networks:
      - staff-network


volumes:
  pgdata-staff:

